!! FE MESH GEN

! DELAUNAY TRIANGULATION: INSERTION KERNEL
! INPUT: POINT TO BE INSERTED = IN, DELAUNAY TRIANGULATION
! {NE,ME,MF}
! OUTPUT: DELAUNAY TRIANGULATION {NE,ME,MF} INCLUDING INSERTED POINT
! IN
! ELEMENT NODE NUMBERS: ME(I), I=1,4*NE
! NEIGHBORING ELEMENTS: MF(I), I=1,4*NE
! NUMBER OF ELEMENTS = NE
! NODAL COORDINATES: X(I),Y(I),Z(I), I=1,NN
! MT(I), I=1,NE : ARRAY TO FLAG DELETED ELEMENTS, MT(I)=1/True:DELETE,
! MT(I)=0/False:KEEP
SUBROUTINE INSERT(NN,IN,NE,ME,MF,MT,X,Y,Z)
    IMPLICIT DOUBLE PRECISION (A-H,O-Z)
    Integer, dimension(1000) :: ME, MF
    Real*8, dimension(1000) :: X, Y, Z
    Integer, dimension(1000) :: MT
    DIMENSION MK(1000),ML(1000),M1(1000),M2(1000),MM(3,4)
    DATA MM/2,4,3,1,3,4,1,4,2,1,2,3/
    ! MK(*),ML(*),M1(*),M2(*): WORKING ARRAYS FOR THE CONSTRUCTION OF
    ! THE CORE
    ! PREPARATION AND SEARCH FOR THE BASE TET KB CONTAINING INSERTION
    ! POINT IN
    XI=X(IN)
    YI=Y(IN)
    ZI=Z(IN)
    CALL BASE (NE,ME,MF,X,Y,Z,IN,KB)
    MT(KB) = 1
    KK=4*KB-4
    NB=0
    NF=0
    DO I=1,4
    KI=MF(KK+I)
    IF (KI.EQ.0) THEN
    NB=NB+1
    M1(NB)=KB
    M2(NB)=I
    ELSE
    NF=NF+1
    MK(NF)=KB
    ML(NF)=I
    ENDIF
    ENDDO
    ! DETERMINE THE BOUNDARY FACETS OF THE CORE:
    ! FACETS SEPARATING DELAUNAY AND NON-DELAUNAY TETS
    ! NB = NUMBER OF BOUNDARY FACETS OF THE CORE
    ! M1(I) = TET SUPPORTING THE FACE I, M2(I) = WHICH FACE OF TET
    ! M1(I), I=1,NB
    1 J=ML(NF)
    K=MK(NF)
    NF=NF-1
    L=MF(4*K-4+J)
    IF (MT(L).NE.0) GOTO 3
    LL=4*L-4
    I1=ME(LL+1)
    I2=ME(LL+2)
    I3=ME(LL+3)
    I4=ME(LL+4)
    CALL SPHERE (I1,I2,I3,I4,X,Y,Z,XX,YY,ZZ,RR)
    IF ((XI-XX)**2+(YI-YY)**2+(ZI-ZZ)**2.LT.RR) THEN
    MT(L)=1
    DO 11 I=1,4
    KI=MF(LL+I)
    IF (KI.EQ.K) GOTO 11
    IF (KI.EQ.0) THEN
    NB=NB+1
    M1(NB)=L
    M2(NB)=I
    ELSE
    NF=NF+1
    MK(NF)=L
    ML(NF)=I
    ENDIF
    11 CONTINUE
    ELSE
    NB=NB+1
    M1(NB)=K
    M2(NB)=J
    ENDIF
    3 IF (NF.GT.0) GOTO 1
    ! CORE VERIFICATION AND CORRECTION: TO BE INSTALLED
    ! FORMING ELEMENTS BY JOINING THE INSERT NODE AND THE BOUNDARY
    ! FACETS
    NA=NE
    DO I=4*NE+1,4*(NE+NB)
    MF(I)=-1
    ENDDO
    DO I=1,NB
    K=M1(I)
    J=M2(I)
    KK=4*K-4
    I1=ME(KK+MM(1,J))
    I2=ME(KK+MM(2,J))
    I3=ME(KK+MM(3,J))
    NE4=NE*4
    ME(NE4+1)=I1
    ME(NE4+2)=I2
    ME(NE4+3)=I3
    ME(NE4+4)=IN
    L=MF(KK+J)
    MF(NE4+4)=L
    NE=NE+1
    MT(NE)=0
    IF (L.NE.0) MF(4*L-4+NEIB(L,MF,K))=NE
    MF(KK+J)=NE
    ENDDO
    ! ESTABLISH THE ADJACENCY RELATIONSHIP
    DO I=1,NB
    JJ=M2(I)
    IT=NA+I
    DO 22 II=1,4
    IF (II.EQ.JJ) GOTO 22
    K=M1(I)
    KK=4*K-4
    J3=ME(KK+II)
    J4=ME(KK+JJ)
    IS=4*IT-4+NODE(IT,ME,J3)
    IF (MF(IS).GE.0) GOTO 22
    J=II

    2 L=MF(4*K-4+J)
    IF (MT(L).NE.0) THEN
    J=NODE(L,ME,J4)
    N=NEIB(L,MF,K)
    J4=ME(4*L-4+N)
    K=L
    GOTO 2
    ENDIF
    MF(IS)=L
    N=NOP(L,IT,ME,J3)
    MF(4*L-4+N)=IT
    22 CONTINUE		
    ENDDO
END

FUNCTION NODE(K,ME,I)
    DIMENSION ME(*)
    ! FIND FROM ELEMENT K THE POSITION OF NODE I
    KK=4*K-4
    DO NODE=1,4
    IF (ME(KK+NODE).EQ.I) RETURN
    ENDDO
    STOP "ERROR IN NODE"
END

FUNCTION NEIB(L,MF,K)
    DIMENSION MF(*)
    ! FIND FROM ELEMENT L THE POSITION OF NEIGHBOURING ELEMENT K
    LL=4*L-4
    DO NEIB=1,4
    IF (MF(LL+NEIB).EQ.K) RETURN
    ENDDO
    STOP "ERROR IN NEIB"
END

FUNCTION NOP(L,K,ME,J)
    DIMENSION ME(*)
    ! FIND FROM ELEMENT L THE POSITION OF THE NODE NOT SHARING WITH
    ! NEIGHBOURING ELEMENT K (OPPOSITE NODE = J)
    KK=4*K-4
    N=ME(KK+1)+ME(KK+2)+ME(KK+3)+ME(KK+4)-J
    LL=4*L-4
    N=ME(LL+1)+ME(LL+2)+ME(LL+3)+ME(LL+4)-N
    DO NOP=1,4
    IF (ME(LL+NOP).EQ.N) RETURN
    ENDDO
    STOP "ERROR IN NOP"
END

SUBROUTINE COMPRESS(NE,ME,MF,MT)
    ! TO CONSOLIDATE ELEMENT STORAGE ME,MF TAKING INTO ACCOUNT OF THE
    ! DELETED
    ! ELEMENTS MT(*)
    Integer :: NE, N, I, J, K, NN
    Integer, dimension(1000) ::  ME, MF
    Integer, dimension(1000) :: MT
    N=NE
    DO 11 I=1,NE
    IF (MT(I).EQ.0) GOTO 11
    II=4*I-4
    N=N+1
    1 N=N-1
    IF (N.LT.I) GOTO 2
    IF (MT(N).NE.0) GOTO 1
    NN=N*4-4
    DO J=1,4
    ME(II+J)=ME(NN+J)
    K=MF(NN+J)
    MF(II+J)=K
    IF (K.GT.0) THEN
    L=NEIB(K,MF,N)
    MF(4*K-4+L)=I
    ENDIF
    ENDDO
    MT(I)=0
    MT(N)=1
    N=N-1
    11 CONTINUE
    2 WRITE (*,*) "ELEMENTS BEFORE AND AFTER COMPRESSION =",NE,N
    NE=N
END

! LOCATE THE BASE TETRAHEDRON K WHICH CONTAINS INSERTED POINT I
SUBROUTINE BASE(NE,ME,MF,X,Y,Z,I,K)
    IMPLICIT DOUBLE PRECISION (A-H,O-Z)
    DIMENSION ME(*),MF(*),X(*),Y(*),Z(*)
    K=NE
    1 KK=4*K-4
    I1=ME(KK+1)
    I2=ME(KK+2)
    I3=ME(KK+3)
    I4=ME(KK+4)
    K1=MF(KK+1)
    K2=MF(KK+2)
    K3=MF(KK+3)
    K4=MF(KK+4)
    V1=VOL(I,I2,I3,I4,X,Y,Z)
    V2=VOL(I1,I,I3,I4,X,Y,Z)
    V3=VOL(I1,I2,I,I4,X,Y,Z)
    V4=VOL(I1,I2,I3,I,X,Y,Z)
    V=VOL(I1,I2,I3,I4,X,Y,Z)
    IF (V1.GE.0.AND.V2.GE.0.AND.V3.GE.0.AND.V4.GE.0) RETURN
    IF (K1.NE.0.AND.V1.LT.V) THEN
    K=K1
    V=V1
    ENDIF
    IF (K2.NE.0.AND.V2.LT.V) THEN
    K=K2
    V=V2
    ENDIF
    IF (K3.NE.0.AND.V3.LT.V) THEN
    K=K3
    V=V3
    ENDIF
    IF (K4.NE.0.AND.V4.LT.V) K=K4
    GOTO 1
END

FUNCTION VOL(I1,I2,I3,I4,X,Y,Z)
    ! COMPUTE THE VOLUME OF TETRAHEDRON I1-I2-I3-I4
    IMPLICIT DOUBLE PRECISION (A-H,O-Z)
    DIMENSION X(*),Y(*),Z(*)
    X1=X(I1)
    Y1=Y(I1)
    Z1=Z(I1)
    A1=X(I2)-X1
    A2=Y(I2)-Y1
    A3=Z(I2)-Z1
    B1=X(I3)-X1
    B2=Y(I3)-Y1
    B3=Z(I3)-Z1
    C1=X(I4)-X1
    C2=Y(I4)-Y1
    C3=Z(I4)-Z1
    VOL=C1*(A2*B3-A3*B2)+C2*(A3*B1-A1*B3)+C3*(A1*B2-A2*B1)
END

SUBROUTINE SPHERE(I1,I2,I3,I4,X,Y,Z,XX,YY,ZZ,RR)
    ! COMPUTE THE CIRCUMSPHERE OF TETRAHEDRON I1-I2-I3-I4
    IMPLICIT DOUBLE PRECISION (A-H,O-Z)
    DIMENSION X(*),Y(*),Z(*)
    X1=X(I1)
    Y1=Y(I1)
    Z1=Z(I1)
    X21=X(I2)-X1
    X31=X(I3)-X1
    X41=X(I4)-X1
    Y21=Y(I2)-Y1
    Y31=Y(I3)-Y1
    Y41=Y(I4)-Y1
    Z21=Z(I2)-Z1
    Z31=Z(I3)-Z1
    Z41=Z(I4)-Z1
    C11=Y31*Z41-Y41*Z31
    C12=Y41*Z21-Y21*Z41
    C13=Y21*Z31-Y31*Z21
    C21=Z31*X41-Z41*X31
    C22=Z41*X21-Z21*X41
    C23=Z21*X31-Z31*X21
    C31=X31*Y41-X41*Y31
    C32=X41*Y21-X21*Y41
    C33=X21*Y31-X31*Y21
    D=2*(X21*C11+Y21*C21+Z21*C31)
    A1=X21**2+Y21**2+Z21**2
    A2=X31**2+Y31**2+Z31**2
    A3=X41**2+Y41**2+Z41**2
    XX=X1+(A1*C11+A2*C12+A3*C13)/D
    YY=Y1+(A1*C21+A2*C22+A3*C23)/D
    ZZ=Z1+(A1*C31+A2*C32+A3*C33)/D
    RR=(XX-X1)**2+(YY-Y1)**2+(ZZ-Z1)**2
END


Program Main 
    ! LOOP TO INSERT POINTS 1 TO NN
    ! NEM = MAXIMUM NUMBER OF ELEMENTS ALLOWED IN ARRAYS ME, MF AND MT
    Implicit None
    Integer :: IN, NN, NEM, NE
    Integer, dimension(1000) :: ME, MF
    Real*8, dimension(1000) :: X, Y, Z
    Integer, dimension(1000) :: MT

    NN = 10
    NEM = 0

    ! NN = 8
    ! Test problem using finer square grid
    ! X(1) = 0.0; Y(1) = 0.0; Z(1) = 0.0
    ! X(2) = 0.5; Y(2) = 0.0; Z(2) = 0.0
    ! X(3) = 1.0; Y(3) = 0.0; Z(3) = 0.0
    ! X(4) = 1.0; Y(4) = 0.5; Z(4) = 0.0
    ! X(5) = 1.0; Y(5) = 1.0; Z(5) = 0.0
    ! X(6) = 0.5; Y(6) = 1.0; Z(6) = 0.0
    ! X(7) = 0.0; Y(7) = 1.0; Z(7) = 0.0
    ! X(8) = 0.0; Y(8) = 0.5; Z(8) = 0.0
    

    DO IN=1,NN
        CALL INSERT(NN,IN,NE,ME,MF,MT,X,Y,Z)
        IF (NE+100 .GT. NEM) Then 
            CALL COMPRESS(NE,ME,MF,MT)
        EndIf
    ENDDO
    CALL COMPRESS(NE,ME,MF,MT)

End Program 